inherit_from: .rubocop_todo.yml

# Double negation is the most convenient way in Ruby to convert any value to boolean. Allow the use of it.
DoubleNegation:
  Enabled: false

WordArray:
  Enabled: false

AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'node_modules/**/*'
    - 'client/node_modules/**/*'
    - 'vendor/bundle/**/*'
    - '.pryrc'
    - 'Procfile.spec'
  TargetRubyVersion: 2.3

Style/RegexpLiteral:
  Enabled: false

# This is enabled by default for Ruby 2.3. It's a good thing to do and
# should be enabled later but requires going through quite a bit of
# code.
Style/FrozenStringLiteralComment:
  Enabled: false
